name: Create release draft

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: show payload
        run: cat $GITHUB_EVENT_PATH
      
      - name: Set tag to env
        run: |
          ref=${{ github.ref }}
          echo "tag=${ref##refs/tags/v}" >> $GITHUB_ENV

      - name: show tag
        run: echo ${{ env.tag }}

      - name: Install nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Create manifest.json
        run: |
          sudo apt install -y gettext-base
          export tag=${{ env.tag }}
          envsubst < manifest.json.template > borderify/manifest.json
          cat borderify/manifest.json

      - name: Sign addon and create addon xpi
        run: |
          cd borderify
          web-ext sign --api-key=${{ secrets.API_KEY }} --api-secret=${{ secrets.API_SECRET }}  --id=`cat ../addon_id`

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            borderify/web-ext-artifacts/my_borderify-${{ env.tag }}-an+fx.xpi

  update_manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set tag to env
        run: |
          ref=${{ github.ref }}
          echo "tag=${ref##refs/tags/v}" >> $GITHUB_ENV

      - name: Install nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          node release.js ${{ env.tag }}
          git add .
          git commit -m "update for release v${{ env.tag }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: update for verison v${{ env.tag }}
          branch: action/release_v${{ env.tag }}
