name: Create release

on:
  push

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display payload
        run: cat $GITHUB_EVENT_PATH

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          draft: true
