name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display payload
        run: cat $GITHUB_EVENT_PATH
      
      - name: Set tag to env
        run: |
          ref=${{ github.ref }}
          echo "tag=${ref##ref/tags/}" >> $GITHUB_ENV

      - name: Create release assets
        run: bash release.sh ${{ env.tag }}
 
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            borderify_${{ env.tag }}.zip

       
